// <auto-generated> Mirrors accesskit_action from accesskit.h (accesskit-c 0.22.2). Do not edit by hand.
namespace AccessKit;

/// <summary>An action that can be requested on an accessibility node. Values match the native accesskit_action enum.</summary>
public enum AkAction : byte
{
    Click = 0,
    Focus = 1,
    Blur = 2,
    Collapse = 3,
    Expand = 4,
    CustomAction = 5,
    Decrement = 6,
    Increment = 7,
    HideTooltip = 8,
    ShowTooltip = 9,
    ReplaceSelectedText = 10,
    ScrollDown = 11,
    ScrollLeft = 12,
    ScrollRight = 13,
    ScrollUp = 14,
    ScrollIntoView = 15,
    ScrollToPoint = 16,
    SetScrollOffset = 17,
    SetTextSelection = 18,
    SetSequentialFocusNavigationStartingPoint = 19,
    SetValue = 20,
    ShowContextMenu = 21,
}
