// <auto-generated>
//   Generated by tools/generate_bindings.py from third-party/accesskit.h (accesskit-c 0.22.2).
//   Do not edit by hand; re-run the generator instead.
// </auto-generated>
namespace AccessKit;

/// <summary>Mirrors <c>accesskit_aria_current</c>. Values match the native enum.</summary>
public enum AriaCurrent : byte
{
    False = 0,
    True = 1,
    Page = 2,
    Step = 3,
    Location = 4,
    Date = 5,
    Time = 6,
}

/// <summary>Mirrors <c>accesskit_auto_complete</c>. Values match the native enum.</summary>
public enum AutoComplete : byte
{
    Inline = 0,
    List = 1,
    Both = 2,
}

/// <summary>Mirrors <c>accesskit_has_popup</c>. Values match the native enum.</summary>
public enum HasPopup : byte
{
    Menu = 0,
    Listbox = 1,
    Tree = 2,
    Grid = 3,
    Dialog = 4,
}

/// <summary>Mirrors <c>accesskit_invalid</c>. Values match the native enum.</summary>
public enum Invalid : byte
{
    True = 0,
    Grammar = 1,
    Spelling = 2,
}

/// <summary>Mirrors <c>accesskit_list_style</c>. Values match the native enum.</summary>
public enum ListStyle : byte
{
    Circle = 0,
    Disc = 1,
    Image = 2,
    Numeric = 3,
    Square = 4,
    Other = 5,
}

/// <summary>Mirrors <c>accesskit_live</c>. Values match the native enum.</summary>
public enum Live : byte
{
    Off = 0,
    Polite = 1,
    Assertive = 2,
}

/// <summary>Mirrors <c>accesskit_orientation</c>. Values match the native enum.</summary>
public enum Orientation : byte
{
    Horizontal = 0,
    Vertical = 1,
}

/// <summary>Mirrors <c>accesskit_scroll_hint</c>. Values match the native enum.</summary>
public enum ScrollHint : byte
{
    TopLeft = 0,
    BottomRight = 1,
    TopEdge = 2,
    BottomEdge = 3,
    LeftEdge = 4,
    RightEdge = 5,
}

/// <summary>Mirrors <c>accesskit_scroll_unit</c>. Values match the native enum.</summary>
public enum ScrollUnit : byte
{
    Item = 0,
    Page = 1,
}

/// <summary>Mirrors <c>accesskit_sort_direction</c>. Values match the native enum.</summary>
public enum SortDirection : byte
{
    Ascending = 0,
    Descending = 1,
    Other = 2,
}

/// <summary>Mirrors <c>accesskit_text_align</c>. Values match the native enum.</summary>
public enum TextAlign : byte
{
    Left = 0,
    Right = 1,
    Center = 2,
    Justify = 3,
}

/// <summary>Mirrors <c>accesskit_text_decoration_style</c>. Values match the native enum.</summary>
public enum TextDecorationStyle : byte
{
    Solid = 0,
    Dotted = 1,
    Dashed = 2,
    Double = 3,
    Wavy = 4,
}

/// <summary>Mirrors <c>accesskit_text_direction</c>. Values match the native enum.</summary>
public enum TextDirection : byte
{
    LeftToRight = 0,
    RightToLeft = 1,
    TopToBottom = 2,
    BottomToTop = 3,
}

/// <summary>Mirrors <c>accesskit_toggled</c>. Values match the native enum.</summary>
public enum Toggled : byte
{
    False = 0,
    True = 1,
    Mixed = 2,
}

/// <summary>Mirrors <c>accesskit_vertical_offset</c>. Values match the native enum.</summary>
public enum VerticalOffset : byte
{
    Subscript = 0,
    Superscript = 1,
}

