// <auto-generated>
//   Generated by tools/generate_bindings.py from third-party/accesskit.h (accesskit-c 0.22.2).
//   The macOS adapter functions (libaccesskit.dylib; only resolvable on macOS).
//   Do not edit by hand; re-run the generator instead.
// </auto-generated>
using System;
using System.Runtime.InteropServices;

namespace AccessKit;

internal static partial class Interop
{
    [DllImport(Lib, CallingConvention = Cc)] public static extern void accesskit_macos_queued_events_raise(IntPtr events);
    [DllImport(Lib, CallingConvention = Cc)] public static extern IntPtr accesskit_macos_adapter_new(IntPtr view, [MarshalAs(UnmanagedType.I1)] bool is_view_focused, ActionHandlerCallback action_handler, IntPtr action_handler_userdata);
    [DllImport(Lib, CallingConvention = Cc)] public static extern void accesskit_macos_adapter_free(IntPtr adapter);
    [DllImport(Lib, CallingConvention = Cc)] public static extern IntPtr accesskit_macos_adapter_update_if_active(IntPtr adapter, TreeUpdateFactory update_factory, IntPtr update_factory_userdata);
    [DllImport(Lib, CallingConvention = Cc)] public static extern IntPtr accesskit_macos_adapter_update_view_focus_state(IntPtr adapter, [MarshalAs(UnmanagedType.I1)] bool is_focused);
    [DllImport(Lib, CallingConvention = Cc)] public static extern IntPtr accesskit_macos_adapter_view_children(IntPtr adapter, ActivationHandlerCallback activation_handler, IntPtr activation_handler_userdata);
    [DllImport(Lib, CallingConvention = Cc)] public static extern IntPtr accesskit_macos_adapter_focus(IntPtr adapter, ActivationHandlerCallback activation_handler, IntPtr activation_handler_userdata);
    [DllImport(Lib, CallingConvention = Cc)] public static extern IntPtr accesskit_macos_adapter_hit_test(IntPtr adapter, double x, double y, ActivationHandlerCallback activation_handler, IntPtr activation_handler_userdata);
    [DllImport(Lib, CallingConvention = Cc)] public static extern IntPtr accesskit_macos_adapter_debug(IntPtr adapter);
    [DllImport(Lib, CallingConvention = Cc)] public static extern IntPtr accesskit_macos_subclassing_adapter_new(IntPtr view, ActivationHandlerCallback activation_handler, IntPtr activation_handler_userdata, ActionHandlerCallback action_handler, IntPtr action_handler_userdata);
    [DllImport(Lib, CallingConvention = Cc)] public static extern IntPtr accesskit_macos_subclassing_adapter_for_window(IntPtr window, ActivationHandlerCallback activation_handler, IntPtr activation_handler_userdata, ActionHandlerCallback action_handler, IntPtr action_handler_userdata);
    [DllImport(Lib, CallingConvention = Cc)] public static extern void accesskit_macos_subclassing_adapter_free(IntPtr adapter);
    [DllImport(Lib, CallingConvention = Cc)] public static extern IntPtr accesskit_macos_subclassing_adapter_update_if_active(IntPtr adapter, TreeUpdateFactory update_factory, IntPtr update_factory_userdata);
    [DllImport(Lib, CallingConvention = Cc)] public static extern IntPtr accesskit_macos_subclassing_adapter_update_view_focus_state(IntPtr adapter, [MarshalAs(UnmanagedType.I1)] bool is_focused);
    [DllImport(Lib, CallingConvention = Cc)] public static extern void accesskit_macos_add_focus_forwarder_to_window_class(byte[] class_name);
    [DllImport(Lib, CallingConvention = Cc)] public static extern void accesskit_macos_add_focus_forwarder_to_window_class_with_length(byte[] class_name, UIntPtr length);
}
