// <auto-generated>
//   Generated by tools/generate_bindings.py from third-party/accesskit.h (accesskit-c 0.22.2).
//   The regular (single-value) node properties. Marshaling-heavy members (strings, id lists,
//   custom actions, transform, actions) are hand-written in Node.cs.
//   Do not edit by hand; re-run the generator instead.
// </auto-generated>
using System;

namespace AccessKit;

public sealed partial class Node
{
    /// <summary>Presence flag <c>hidden</c>.</summary>
    public bool Hidden
    {
        get => Interop.accesskit_node_is_hidden(_handle);
        set { if (value) Interop.accesskit_node_set_hidden(_handle); else Interop.accesskit_node_clear_hidden(_handle); }
    }

    /// <summary>Presence flag <c>multiselectable</c>.</summary>
    public bool Multiselectable
    {
        get => Interop.accesskit_node_is_multiselectable(_handle);
        set { if (value) Interop.accesskit_node_set_multiselectable(_handle); else Interop.accesskit_node_clear_multiselectable(_handle); }
    }

    /// <summary>Presence flag <c>required</c>.</summary>
    public bool Required
    {
        get => Interop.accesskit_node_is_required(_handle);
        set { if (value) Interop.accesskit_node_set_required(_handle); else Interop.accesskit_node_clear_required(_handle); }
    }

    /// <summary>Presence flag <c>visited</c>.</summary>
    public bool Visited
    {
        get => Interop.accesskit_node_is_visited(_handle);
        set { if (value) Interop.accesskit_node_set_visited(_handle); else Interop.accesskit_node_clear_visited(_handle); }
    }

    /// <summary>Presence flag <c>busy</c>.</summary>
    public bool Busy
    {
        get => Interop.accesskit_node_is_busy(_handle);
        set { if (value) Interop.accesskit_node_set_busy(_handle); else Interop.accesskit_node_clear_busy(_handle); }
    }

    /// <summary>Presence flag <c>live_atomic</c>.</summary>
    public bool LiveAtomic
    {
        get => Interop.accesskit_node_is_live_atomic(_handle);
        set { if (value) Interop.accesskit_node_set_live_atomic(_handle); else Interop.accesskit_node_clear_live_atomic(_handle); }
    }

    /// <summary>Presence flag <c>modal</c>.</summary>
    public bool Modal
    {
        get => Interop.accesskit_node_is_modal(_handle);
        set { if (value) Interop.accesskit_node_set_modal(_handle); else Interop.accesskit_node_clear_modal(_handle); }
    }

    /// <summary>Presence flag <c>touch_transparent</c>.</summary>
    public bool TouchTransparent
    {
        get => Interop.accesskit_node_is_touch_transparent(_handle);
        set { if (value) Interop.accesskit_node_set_touch_transparent(_handle); else Interop.accesskit_node_clear_touch_transparent(_handle); }
    }

    /// <summary>Presence flag <c>read_only</c>.</summary>
    public bool ReadOnly
    {
        get => Interop.accesskit_node_is_read_only(_handle);
        set { if (value) Interop.accesskit_node_set_read_only(_handle); else Interop.accesskit_node_clear_read_only(_handle); }
    }

    /// <summary>Presence flag <c>disabled</c>.</summary>
    public bool Disabled
    {
        get => Interop.accesskit_node_is_disabled(_handle);
        set { if (value) Interop.accesskit_node_set_disabled(_handle); else Interop.accesskit_node_clear_disabled(_handle); }
    }

    /// <summary>Presence flag <c>italic</c>.</summary>
    public bool Italic
    {
        get => Interop.accesskit_node_is_italic(_handle);
        set { if (value) Interop.accesskit_node_set_italic(_handle); else Interop.accesskit_node_clear_italic(_handle); }
    }

    /// <summary>Presence flag <c>clips_children</c>.</summary>
    public bool ClipsChildren
    {
        get => Interop.accesskit_node_clips_children(_handle);
        set { if (value) Interop.accesskit_node_set_clips_children(_handle); else Interop.accesskit_node_clear_clips_children(_handle); }
    }

    /// <summary>Presence flag <c>is_line_breaking_object</c>.</summary>
    public bool IsLineBreakingObject
    {
        get => Interop.accesskit_node_is_line_breaking_object(_handle);
        set { if (value) Interop.accesskit_node_set_is_line_breaking_object(_handle); else Interop.accesskit_node_clear_is_line_breaking_object(_handle); }
    }

    /// <summary>Presence flag <c>is_page_breaking_object</c>.</summary>
    public bool IsPageBreakingObject
    {
        get => Interop.accesskit_node_is_page_breaking_object(_handle);
        set { if (value) Interop.accesskit_node_set_is_page_breaking_object(_handle); else Interop.accesskit_node_clear_is_page_breaking_object(_handle); }
    }

    /// <summary>Presence flag <c>is_spelling_error</c>.</summary>
    public bool IsSpellingError
    {
        get => Interop.accesskit_node_is_spelling_error(_handle);
        set { if (value) Interop.accesskit_node_set_is_spelling_error(_handle); else Interop.accesskit_node_clear_is_spelling_error(_handle); }
    }

    /// <summary>Presence flag <c>is_grammar_error</c>.</summary>
    public bool IsGrammarError
    {
        get => Interop.accesskit_node_is_grammar_error(_handle);
        set { if (value) Interop.accesskit_node_set_is_grammar_error(_handle); else Interop.accesskit_node_clear_is_grammar_error(_handle); }
    }

    /// <summary>Presence flag <c>is_search_match</c>.</summary>
    public bool IsSearchMatch
    {
        get => Interop.accesskit_node_is_search_match(_handle);
        set { if (value) Interop.accesskit_node_set_is_search_match(_handle); else Interop.accesskit_node_clear_is_search_match(_handle); }
    }

    /// <summary>Presence flag <c>is_suggestion</c>.</summary>
    public bool IsSuggestion
    {
        get => Interop.accesskit_node_is_suggestion(_handle);
        set { if (value) Interop.accesskit_node_set_is_suggestion(_handle); else Interop.accesskit_node_clear_is_suggestion(_handle); }
    }

    /// <summary>Tri-state <c>expanded</c> (null = unset).</summary>
    public bool? Expanded
    {
        get { var o = Interop.accesskit_node_is_expanded(_handle); return o.HasValue != 0 ? o.Value != 0 : (bool?)null; }
        set { if (value.HasValue) Interop.accesskit_node_set_expanded(_handle, value.Value); else Interop.accesskit_node_clear_expanded(_handle); }
    }

    /// <summary>Tri-state <c>selected</c> (null = unset).</summary>
    public bool? Selected
    {
        get { var o = Interop.accesskit_node_is_selected(_handle); return o.HasValue != 0 ? o.Value != 0 : (bool?)null; }
        set { if (value.HasValue) Interop.accesskit_node_set_selected(_handle, value.Value); else Interop.accesskit_node_clear_selected(_handle); }
    }

    /// <summary><c>scroll_x</c> (null = unset).</summary>
    public double? ScrollX
    {
        get { var o = Interop.accesskit_node_scroll_x(_handle); return o.HasValue != 0 ? o.Value : (double?)null; }
        set { if (value.HasValue) Interop.accesskit_node_set_scroll_x(_handle, value.Value); else Interop.accesskit_node_clear_scroll_x(_handle); }
    }

    /// <summary><c>scroll_x_min</c> (null = unset).</summary>
    public double? ScrollXMin
    {
        get { var o = Interop.accesskit_node_scroll_x_min(_handle); return o.HasValue != 0 ? o.Value : (double?)null; }
        set { if (value.HasValue) Interop.accesskit_node_set_scroll_x_min(_handle, value.Value); else Interop.accesskit_node_clear_scroll_x_min(_handle); }
    }

    /// <summary><c>scroll_x_max</c> (null = unset).</summary>
    public double? ScrollXMax
    {
        get { var o = Interop.accesskit_node_scroll_x_max(_handle); return o.HasValue != 0 ? o.Value : (double?)null; }
        set { if (value.HasValue) Interop.accesskit_node_set_scroll_x_max(_handle, value.Value); else Interop.accesskit_node_clear_scroll_x_max(_handle); }
    }

    /// <summary><c>scroll_y</c> (null = unset).</summary>
    public double? ScrollY
    {
        get { var o = Interop.accesskit_node_scroll_y(_handle); return o.HasValue != 0 ? o.Value : (double?)null; }
        set { if (value.HasValue) Interop.accesskit_node_set_scroll_y(_handle, value.Value); else Interop.accesskit_node_clear_scroll_y(_handle); }
    }

    /// <summary><c>scroll_y_min</c> (null = unset).</summary>
    public double? ScrollYMin
    {
        get { var o = Interop.accesskit_node_scroll_y_min(_handle); return o.HasValue != 0 ? o.Value : (double?)null; }
        set { if (value.HasValue) Interop.accesskit_node_set_scroll_y_min(_handle, value.Value); else Interop.accesskit_node_clear_scroll_y_min(_handle); }
    }

    /// <summary><c>scroll_y_max</c> (null = unset).</summary>
    public double? ScrollYMax
    {
        get { var o = Interop.accesskit_node_scroll_y_max(_handle); return o.HasValue != 0 ? o.Value : (double?)null; }
        set { if (value.HasValue) Interop.accesskit_node_set_scroll_y_max(_handle, value.Value); else Interop.accesskit_node_clear_scroll_y_max(_handle); }
    }

    /// <summary><c>numeric_value</c> (null = unset).</summary>
    public double? NumericValue
    {
        get { var o = Interop.accesskit_node_numeric_value(_handle); return o.HasValue != 0 ? o.Value : (double?)null; }
        set { if (value.HasValue) Interop.accesskit_node_set_numeric_value(_handle, value.Value); else Interop.accesskit_node_clear_numeric_value(_handle); }
    }

    /// <summary><c>min_numeric_value</c> (null = unset).</summary>
    public double? MinNumericValue
    {
        get { var o = Interop.accesskit_node_min_numeric_value(_handle); return o.HasValue != 0 ? o.Value : (double?)null; }
        set { if (value.HasValue) Interop.accesskit_node_set_min_numeric_value(_handle, value.Value); else Interop.accesskit_node_clear_min_numeric_value(_handle); }
    }

    /// <summary><c>max_numeric_value</c> (null = unset).</summary>
    public double? MaxNumericValue
    {
        get { var o = Interop.accesskit_node_max_numeric_value(_handle); return o.HasValue != 0 ? o.Value : (double?)null; }
        set { if (value.HasValue) Interop.accesskit_node_set_max_numeric_value(_handle, value.Value); else Interop.accesskit_node_clear_max_numeric_value(_handle); }
    }

    /// <summary><c>numeric_value_step</c> (null = unset).</summary>
    public double? NumericValueStep
    {
        get { var o = Interop.accesskit_node_numeric_value_step(_handle); return o.HasValue != 0 ? o.Value : (double?)null; }
        set { if (value.HasValue) Interop.accesskit_node_set_numeric_value_step(_handle, value.Value); else Interop.accesskit_node_clear_numeric_value_step(_handle); }
    }

    /// <summary><c>numeric_value_jump</c> (null = unset).</summary>
    public double? NumericValueJump
    {
        get { var o = Interop.accesskit_node_numeric_value_jump(_handle); return o.HasValue != 0 ? o.Value : (double?)null; }
        set { if (value.HasValue) Interop.accesskit_node_set_numeric_value_jump(_handle, value.Value); else Interop.accesskit_node_clear_numeric_value_jump(_handle); }
    }

    /// <summary><c>font_size</c> (null = unset).</summary>
    public float? FontSize
    {
        get { var o = Interop.accesskit_node_font_size(_handle); return o.HasValue != 0 ? o.Value : (float?)null; }
        set { if (value.HasValue) Interop.accesskit_node_set_font_size(_handle, value.Value); else Interop.accesskit_node_clear_font_size(_handle); }
    }

    /// <summary><c>font_weight</c> (null = unset).</summary>
    public float? FontWeight
    {
        get { var o = Interop.accesskit_node_font_weight(_handle); return o.HasValue != 0 ? o.Value : (float?)null; }
        set { if (value.HasValue) Interop.accesskit_node_set_font_weight(_handle, value.Value); else Interop.accesskit_node_clear_font_weight(_handle); }
    }

    /// <summary><c>row_count</c> (null = unset).</summary>
    public int? RowCount
    {
        get { var o = Interop.accesskit_node_row_count(_handle); return o.HasValue != 0 ? (int)(uint)o.Value : (int?)null; }
        set { if (value.HasValue) Interop.accesskit_node_set_row_count(_handle, (UIntPtr)(uint)value.Value); else Interop.accesskit_node_clear_row_count(_handle); }
    }

    /// <summary><c>column_count</c> (null = unset).</summary>
    public int? ColumnCount
    {
        get { var o = Interop.accesskit_node_column_count(_handle); return o.HasValue != 0 ? (int)(uint)o.Value : (int?)null; }
        set { if (value.HasValue) Interop.accesskit_node_set_column_count(_handle, (UIntPtr)(uint)value.Value); else Interop.accesskit_node_clear_column_count(_handle); }
    }

    /// <summary><c>row_index</c> (null = unset).</summary>
    public int? RowIndex
    {
        get { var o = Interop.accesskit_node_row_index(_handle); return o.HasValue != 0 ? (int)(uint)o.Value : (int?)null; }
        set { if (value.HasValue) Interop.accesskit_node_set_row_index(_handle, (UIntPtr)(uint)value.Value); else Interop.accesskit_node_clear_row_index(_handle); }
    }

    /// <summary><c>column_index</c> (null = unset).</summary>
    public int? ColumnIndex
    {
        get { var o = Interop.accesskit_node_column_index(_handle); return o.HasValue != 0 ? (int)(uint)o.Value : (int?)null; }
        set { if (value.HasValue) Interop.accesskit_node_set_column_index(_handle, (UIntPtr)(uint)value.Value); else Interop.accesskit_node_clear_column_index(_handle); }
    }

    /// <summary><c>row_span</c> (null = unset).</summary>
    public int? RowSpan
    {
        get { var o = Interop.accesskit_node_row_span(_handle); return o.HasValue != 0 ? (int)(uint)o.Value : (int?)null; }
        set { if (value.HasValue) Interop.accesskit_node_set_row_span(_handle, (UIntPtr)(uint)value.Value); else Interop.accesskit_node_clear_row_span(_handle); }
    }

    /// <summary><c>column_span</c> (null = unset).</summary>
    public int? ColumnSpan
    {
        get { var o = Interop.accesskit_node_column_span(_handle); return o.HasValue != 0 ? (int)(uint)o.Value : (int?)null; }
        set { if (value.HasValue) Interop.accesskit_node_set_column_span(_handle, (UIntPtr)(uint)value.Value); else Interop.accesskit_node_clear_column_span(_handle); }
    }

    /// <summary><c>level</c> (null = unset).</summary>
    public int? Level
    {
        get { var o = Interop.accesskit_node_level(_handle); return o.HasValue != 0 ? (int)(uint)o.Value : (int?)null; }
        set { if (value.HasValue) Interop.accesskit_node_set_level(_handle, (UIntPtr)(uint)value.Value); else Interop.accesskit_node_clear_level(_handle); }
    }

    /// <summary><c>size_of_set</c> (null = unset).</summary>
    public int? SizeOfSet
    {
        get { var o = Interop.accesskit_node_size_of_set(_handle); return o.HasValue != 0 ? (int)(uint)o.Value : (int?)null; }
        set { if (value.HasValue) Interop.accesskit_node_set_size_of_set(_handle, (UIntPtr)(uint)value.Value); else Interop.accesskit_node_clear_size_of_set(_handle); }
    }

    /// <summary><c>position_in_set</c> (null = unset).</summary>
    public int? PositionInSet
    {
        get { var o = Interop.accesskit_node_position_in_set(_handle); return o.HasValue != 0 ? (int)(uint)o.Value : (int?)null; }
        set { if (value.HasValue) Interop.accesskit_node_set_position_in_set(_handle, (UIntPtr)(uint)value.Value); else Interop.accesskit_node_clear_position_in_set(_handle); }
    }

    /// <summary><c>color_value</c> (null = unset).</summary>
    public Color? ColorValue
    {
        get { var o = Interop.accesskit_node_color_value(_handle); return o.HasValue != 0 ? o.Value : (Color?)null; }
        set { if (value.HasValue) Interop.accesskit_node_set_color_value(_handle, value.Value); else Interop.accesskit_node_clear_color_value(_handle); }
    }

    /// <summary><c>background_color</c> (null = unset).</summary>
    public Color? BackgroundColor
    {
        get { var o = Interop.accesskit_node_background_color(_handle); return o.HasValue != 0 ? o.Value : (Color?)null; }
        set { if (value.HasValue) Interop.accesskit_node_set_background_color(_handle, value.Value); else Interop.accesskit_node_clear_background_color(_handle); }
    }

    /// <summary><c>foreground_color</c> (null = unset).</summary>
    public Color? ForegroundColor
    {
        get { var o = Interop.accesskit_node_foreground_color(_handle); return o.HasValue != 0 ? o.Value : (Color?)null; }
        set { if (value.HasValue) Interop.accesskit_node_set_foreground_color(_handle, value.Value); else Interop.accesskit_node_clear_foreground_color(_handle); }
    }

    /// <summary><c>overline</c> text decoration (null = unset).</summary>
    public TextDecoration? Overline
    {
        get { var o = Interop.accesskit_node_overline(_handle); return o.HasValue != 0 ? o.Value : (TextDecoration?)null; }
        set { if (value.HasValue) Interop.accesskit_node_set_overline(_handle, value.Value); else Interop.accesskit_node_clear_overline(_handle); }
    }

    /// <summary><c>strikethrough</c> text decoration (null = unset).</summary>
    public TextDecoration? Strikethrough
    {
        get { var o = Interop.accesskit_node_strikethrough(_handle); return o.HasValue != 0 ? o.Value : (TextDecoration?)null; }
        set { if (value.HasValue) Interop.accesskit_node_set_strikethrough(_handle, value.Value); else Interop.accesskit_node_clear_strikethrough(_handle); }
    }

    /// <summary><c>underline</c> text decoration (null = unset).</summary>
    public TextDecoration? Underline
    {
        get { var o = Interop.accesskit_node_underline(_handle); return o.HasValue != 0 ? o.Value : (TextDecoration?)null; }
        set { if (value.HasValue) Interop.accesskit_node_set_underline(_handle, value.Value); else Interop.accesskit_node_clear_underline(_handle); }
    }

    /// <summary><c>invalid</c> (null = unset).</summary>
    public Invalid? Invalid
    {
        get { var o = Interop.accesskit_node_invalid(_handle); return o.HasValue != 0 ? o.Value : (Invalid?)null; }
        set { if (value.HasValue) Interop.accesskit_node_set_invalid(_handle, value.Value); else Interop.accesskit_node_clear_invalid(_handle); }
    }

    /// <summary><c>toggled</c> (null = unset).</summary>
    public Toggled? Toggled
    {
        get { var o = Interop.accesskit_node_toggled(_handle); return o.HasValue != 0 ? o.Value : (Toggled?)null; }
        set { if (value.HasValue) Interop.accesskit_node_set_toggled(_handle, value.Value); else Interop.accesskit_node_clear_toggled(_handle); }
    }

    /// <summary><c>live</c> (null = unset).</summary>
    public Live? Live
    {
        get { var o = Interop.accesskit_node_live(_handle); return o.HasValue != 0 ? o.Value : (Live?)null; }
        set { if (value.HasValue) Interop.accesskit_node_set_live(_handle, value.Value); else Interop.accesskit_node_clear_live(_handle); }
    }

    /// <summary><c>text_direction</c> (null = unset).</summary>
    public TextDirection? TextDirection
    {
        get { var o = Interop.accesskit_node_text_direction(_handle); return o.HasValue != 0 ? o.Value : (TextDirection?)null; }
        set { if (value.HasValue) Interop.accesskit_node_set_text_direction(_handle, value.Value); else Interop.accesskit_node_clear_text_direction(_handle); }
    }

    /// <summary><c>orientation</c> (null = unset).</summary>
    public Orientation? Orientation
    {
        get { var o = Interop.accesskit_node_orientation(_handle); return o.HasValue != 0 ? o.Value : (Orientation?)null; }
        set { if (value.HasValue) Interop.accesskit_node_set_orientation(_handle, value.Value); else Interop.accesskit_node_clear_orientation(_handle); }
    }

    /// <summary><c>sort_direction</c> (null = unset).</summary>
    public SortDirection? SortDirection
    {
        get { var o = Interop.accesskit_node_sort_direction(_handle); return o.HasValue != 0 ? o.Value : (SortDirection?)null; }
        set { if (value.HasValue) Interop.accesskit_node_set_sort_direction(_handle, value.Value); else Interop.accesskit_node_clear_sort_direction(_handle); }
    }

    /// <summary><c>aria_current</c> (null = unset).</summary>
    public AriaCurrent? AriaCurrent
    {
        get { var o = Interop.accesskit_node_aria_current(_handle); return o.HasValue != 0 ? o.Value : (AriaCurrent?)null; }
        set { if (value.HasValue) Interop.accesskit_node_set_aria_current(_handle, value.Value); else Interop.accesskit_node_clear_aria_current(_handle); }
    }

    /// <summary><c>auto_complete</c> (null = unset).</summary>
    public AutoComplete? AutoComplete
    {
        get { var o = Interop.accesskit_node_auto_complete(_handle); return o.HasValue != 0 ? o.Value : (AutoComplete?)null; }
        set { if (value.HasValue) Interop.accesskit_node_set_auto_complete(_handle, value.Value); else Interop.accesskit_node_clear_auto_complete(_handle); }
    }

    /// <summary><c>has_popup</c> (null = unset).</summary>
    public HasPopup? HasPopup
    {
        get { var o = Interop.accesskit_node_has_popup(_handle); return o.HasValue != 0 ? o.Value : (HasPopup?)null; }
        set { if (value.HasValue) Interop.accesskit_node_set_has_popup(_handle, value.Value); else Interop.accesskit_node_clear_has_popup(_handle); }
    }

    /// <summary><c>list_style</c> (null = unset).</summary>
    public ListStyle? ListStyle
    {
        get { var o = Interop.accesskit_node_list_style(_handle); return o.HasValue != 0 ? o.Value : (ListStyle?)null; }
        set { if (value.HasValue) Interop.accesskit_node_set_list_style(_handle, value.Value); else Interop.accesskit_node_clear_list_style(_handle); }
    }

    /// <summary><c>text_align</c> (null = unset).</summary>
    public TextAlign? TextAlign
    {
        get { var o = Interop.accesskit_node_text_align(_handle); return o.HasValue != 0 ? o.Value : (TextAlign?)null; }
        set { if (value.HasValue) Interop.accesskit_node_set_text_align(_handle, value.Value); else Interop.accesskit_node_clear_text_align(_handle); }
    }

    /// <summary><c>vertical_offset</c> (null = unset).</summary>
    public VerticalOffset? VerticalOffset
    {
        get { var o = Interop.accesskit_node_vertical_offset(_handle); return o.HasValue != 0 ? o.Value : (VerticalOffset?)null; }
        set { if (value.HasValue) Interop.accesskit_node_set_vertical_offset(_handle, value.Value); else Interop.accesskit_node_clear_vertical_offset(_handle); }
    }

    /// <summary><c>active_descendant</c> node id (null = unset).</summary>
    public ulong? ActiveDescendant
    {
        get { var o = Interop.accesskit_node_active_descendant(_handle); return o.HasValue != 0 ? o.Value : (ulong?)null; }
        set { if (value.HasValue) Interop.accesskit_node_set_active_descendant(_handle, value.Value); else Interop.accesskit_node_clear_active_descendant(_handle); }
    }

    /// <summary><c>error_message</c> node id (null = unset).</summary>
    public ulong? ErrorMessage
    {
        get { var o = Interop.accesskit_node_error_message(_handle); return o.HasValue != 0 ? o.Value : (ulong?)null; }
        set { if (value.HasValue) Interop.accesskit_node_set_error_message(_handle, value.Value); else Interop.accesskit_node_clear_error_message(_handle); }
    }

    /// <summary><c>in_page_link_target</c> node id (null = unset).</summary>
    public ulong? InPageLinkTarget
    {
        get { var o = Interop.accesskit_node_in_page_link_target(_handle); return o.HasValue != 0 ? o.Value : (ulong?)null; }
        set { if (value.HasValue) Interop.accesskit_node_set_in_page_link_target(_handle, value.Value); else Interop.accesskit_node_clear_in_page_link_target(_handle); }
    }

    /// <summary><c>member_of</c> node id (null = unset).</summary>
    public ulong? MemberOf
    {
        get { var o = Interop.accesskit_node_member_of(_handle); return o.HasValue != 0 ? o.Value : (ulong?)null; }
        set { if (value.HasValue) Interop.accesskit_node_set_member_of(_handle, value.Value); else Interop.accesskit_node_clear_member_of(_handle); }
    }

    /// <summary><c>next_on_line</c> node id (null = unset).</summary>
    public ulong? NextOnLine
    {
        get { var o = Interop.accesskit_node_next_on_line(_handle); return o.HasValue != 0 ? o.Value : (ulong?)null; }
        set { if (value.HasValue) Interop.accesskit_node_set_next_on_line(_handle, value.Value); else Interop.accesskit_node_clear_next_on_line(_handle); }
    }

    /// <summary><c>previous_on_line</c> node id (null = unset).</summary>
    public ulong? PreviousOnLine
    {
        get { var o = Interop.accesskit_node_previous_on_line(_handle); return o.HasValue != 0 ? o.Value : (ulong?)null; }
        set { if (value.HasValue) Interop.accesskit_node_set_previous_on_line(_handle, value.Value); else Interop.accesskit_node_clear_previous_on_line(_handle); }
    }

    /// <summary><c>popup_for</c> node id (null = unset).</summary>
    public ulong? PopupFor
    {
        get { var o = Interop.accesskit_node_popup_for(_handle); return o.HasValue != 0 ? o.Value : (ulong?)null; }
        set { if (value.HasValue) Interop.accesskit_node_set_popup_for(_handle, value.Value); else Interop.accesskit_node_clear_popup_for(_handle); }
    }

    /// <summary>Bounding box in the window coordinate space (y-down); null = unset.</summary>
    public Rect? Bounds
    {
        get { var o = Interop.accesskit_node_bounds(_handle); return o.HasValue != 0 ? o.Value : (Rect?)null; }
        set { if (value.HasValue) Interop.accesskit_node_set_bounds(_handle, value.Value); else Interop.accesskit_node_clear_bounds(_handle); }
    }

    /// <summary>Text selection within this node (null = unset).</summary>
    public TextSelection? TextSelection
    {
        get { var o = Interop.accesskit_node_text_selection(_handle); return o.HasValue != 0 ? o.Value : (TextSelection?)null; }
        set { if (value.HasValue) Interop.accesskit_node_set_text_selection(_handle, value.Value); else Interop.accesskit_node_clear_text_selection(_handle); }
    }

    /// <summary>The id of a subtree hosted by this node (null = unset).</summary>
    public TreeId? TreeId
    {
        get { var o = Interop.accesskit_node_tree_id(_handle); return o.HasValue != 0 ? o.Value : (TreeId?)null; }
        set { if (value.HasValue) Interop.accesskit_node_set_tree_id(_handle, value.Value); else Interop.accesskit_node_clear_tree_id(_handle); }
    }

}
