#!/usr/bin/env python3
"""Generates the AccessKit.NET P/Invoke layer and enums from third-party/accesskit.h.

Run from the repo root:  python tools/generate_bindings.py

Emits (overwriting):
  src/AccessKit.NET/Interop.Generated.cs   -- one DllImport per exported function
  src/AccessKit.NET/Enums.Generated.cs      -- every accesskit_* enum except Role/AkAction

Only functions actually exported by the bundled win-x64 accesskit.dll are bound; the
platform-gated (Android/iOS/macOS/Unix) declarations in the header are skipped. The export
set is read from the header's non-gated declarations (the header gates them with #if), so a
plain parse that drops nothing inside #if blocks for other platforms is used.

Hand-written files (Structs.cs, Node.cs, geometry, adapters, ...) build on top of this.
"""
import re
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HEADER = os.path.join(ROOT, 'third-party', 'accesskit.h')
OUT_DIR = os.path.join(ROOT, 'src', 'AccessKit.NET')

# Enums that already have hand-tuned files we keep as-is.
SKIP_ENUMS = {'accesskit_role', 'accesskit_action'}

# accesskit_<c_enum>  ->  C# enum name
ENUM_CS = {
    'accesskit_action': 'AkAction',
    'accesskit_role': 'Role',
    'accesskit_aria_current': 'AriaCurrent',
    'accesskit_auto_complete': 'AutoComplete',
    'accesskit_has_popup': 'HasPopup',
    'accesskit_invalid': 'Invalid',
    'accesskit_list_style': 'ListStyle',
    'accesskit_live': 'Live',
    'accesskit_orientation': 'Orientation',
    'accesskit_scroll_hint': 'ScrollHint',
    'accesskit_scroll_unit': 'ScrollUnit',
    'accesskit_sort_direction': 'SortDirection',
    'accesskit_text_align': 'TextAlign',
    'accesskit_text_decoration_style': 'TextDecorationStyle',
    'accesskit_text_direction': 'TextDirection',
    'accesskit_toggled': 'Toggled',
    'accesskit_vertical_offset': 'VerticalOffset',
}


def strip_comments(src):
    src = re.sub(r'/\*.*?\*/', '', src, flags=re.S)
    src = re.sub(r'//.*', '', src)
    return src


def to_pascal(token):
    """ACCESSKIT_ARIA_CURRENT_TRUE with prefix ACCESSKIT_ARIA_CURRENT_ -> True"""
    parts = token.split('_')
    return ''.join(p.capitalize() for p in parts)


# ---------------------------------------------------------------- enums
def parse_enums(src):
    """Returns list of (c_name, [member_tokens])."""
    out = []
    for m in re.finditer(r'enum\s+(accesskit_\w+)\b[^{]*\{([^}]*)\}', src, flags=re.S):
        name = m.group(1)
        body = m.group(2)
        members = []
        for line in body.split(','):
            line = line.strip()
            if not line:
                continue
            mm = re.match(r'(ACCESSKIT_\w+)', line)
            if mm:
                members.append(mm.group(1))
        if members:
            out.append((name, members))
    return out


def emit_enums(enums):
    lines = [
        '// <auto-generated>',
        '//   Generated by tools/generate_bindings.py from third-party/accesskit.h (accesskit-c 0.22.2).',
        '//   Do not edit by hand; re-run the generator instead.',
        '// </auto-generated>',
        'namespace AccessKit;',
        '',
    ]
    for c_name, members in enums:
        if c_name in SKIP_ENUMS or c_name not in ENUM_CS:
            continue
        cs = ENUM_CS[c_name]
        prefix = 'ACCESSKIT_' + cs_to_screaming(c_name)
        lines.append(f'/// <summary>Mirrors <c>{c_name}</c>. Values match the native enum.</summary>')
        lines.append(f'public enum {cs} : byte')
        lines.append('{')
        for i, mtok in enumerate(members):
            short = mtok
            common = 'ACCESSKIT_' + c_name[len('accesskit_'):].upper() + '_'
            if short.startswith(common):
                short = short[len(common):]
            lines.append(f'    {to_pascal(short)} = {i},')
        lines.append('}')
        lines.append('')
    return '\n'.join(lines)


def cs_to_screaming(c_name):
    return c_name[len('accesskit_'):].upper()


# ---------------------------------------------------------------- functions
def parse_funcs(src):
    text = re.sub(r'\s+', ' ', src)
    decls = re.findall(
        r'([A-Za-z_][\w \*]*?)\b(accesskit_[a-z0-9_]+)\s*\(([^;{]*?)\)\s*;', text)
    seen = set()
    out = []
    for ret, name, params in decls:
        if name in seen:
            continue
        seen.add(name)
        out.append((norm(ret), name, norm(params)))
    return out


def norm(t):
    return re.sub(r'\s+', ' ', t).strip()


def split_params(params):
    params = norm(params)
    if params in ('void', ''):
        return []
    return [p.strip() for p in params.split(',')]


def split_type_name(p):
    """'const struct accesskit_node *node' -> ('const struct accesskit_node *', 'node')."""
    p = norm(p)
    # pointer-to-pointer / pointer params keep the * with the type
    m = re.match(r'^(.*?)(\*?\s*)([A-Za-z_]\w*)$', p)
    # Find the last identifier as the name only if the char before it isn't part of type.
    m = re.match(r'^(.*[ \*])([A-Za-z_]\w*)$', p)
    if m:
        return norm(m.group(1)), m.group(2)
    return p, ''


# C type -> (cs_interop_type, param_attr_prefix)
# param_attr_prefix is text placed before the type in a parameter declaration.
def map_param(ct):
    ct = norm(ct)
    # blittable struct receivers passed by const pointer
    if ct == 'const struct accesskit_rect *':
        return 'in Rect', ''
    if ct == 'const struct accesskit_affine *':
        return 'in Affine', ''
    # opaque handles / void*
    OPAQUE = {
        'struct accesskit_node *', 'const struct accesskit_node *',
        'struct accesskit_tree *', 'const struct accesskit_tree *',
        'struct accesskit_tree_update *', 'const struct accesskit_tree_update *',
        'struct accesskit_custom_action *', 'const struct accesskit_custom_action *',
        'struct accesskit_custom_action *const *',
        'struct accesskit_custom_actions *',
        'struct accesskit_action_request *',
        'struct accesskit_windows_adapter *', 'const struct accesskit_windows_adapter *',
        'struct accesskit_windows_queued_events *',
        'struct accesskit_windows_subclassing_adapter *',
        'struct accesskit_macos_adapter *', 'const struct accesskit_macos_adapter *',
        'struct accesskit_macos_queued_events *',
        'struct accesskit_macos_subclassing_adapter *',
        'void *', 'HWND', 'WPARAM', 'LPARAM',
    }
    if ct in OPAQUE:
        return 'IntPtr', ''
    if ct == 'struct accesskit_custom_action *const *':
        return 'IntPtr[]', ''
    # arrays
    if ct == 'const accesskit_node_id *':
        return 'ulong[]', '[In] '
    if ct == 'const float *':
        return 'float[]', '[In] '
    if ct == 'const uint8_t *':
        return 'byte[]', '[In] '
    # setters take `const char*` (UTF-8 input); we pass a byte[] we build.
    if ct == 'const char *':
        return 'byte[]', ''
    # a non-const `char*` param is an AccessKit-owned pointer being handed back
    # (e.g. accesskit_string_free) -> pass the raw pointer.
    if ct == 'char *':
        return 'IntPtr', ''
    # by-value structs
    BYVAL = {
        'struct accesskit_affine': 'Affine',
        'struct accesskit_color': 'Color',
        'struct accesskit_point': 'Point',
        'struct accesskit_size': 'Size',
        'struct accesskit_vec2': 'Vec2',
        'struct accesskit_rect': 'Rect',
        'struct accesskit_text_decoration': 'TextDecoration',
        'struct accesskit_text_selection': 'TextSelection',
        'struct accesskit_tree_id': 'TreeId',
    }
    if ct in BYVAL:
        return BYVAL[ct], ''
    # scalars / enums / callbacks
    SCALAR = {
        'accesskit_node_id': 'ulong',
        'double': 'double',
        'float': 'float',
        'int32_t': 'int',
        'size_t': 'UIntPtr',
        'bool': 'bool',
        'accesskit_action_handler_callback': 'ActionHandlerCallback',
        'accesskit_activation_handler_callback': 'ActivationHandlerCallback',
        'accesskit_tree_update_factory': 'TreeUpdateFactory',
    }
    if ct in SCALAR:
        if ct == 'bool':
            return 'bool', '[MarshalAs(UnmanagedType.I1)] '
        return SCALAR[ct], ''
    if ct in ENUM_CS:
        return ENUM_CS[ct], ''
    raise SystemExit(f'Unmapped param type: {ct!r}')


def map_return(ct):
    """Returns (cs_type, return_attr_line_or_empty)."""
    ct = norm(ct)
    if ct == 'void':
        return 'void', ''
    if ct == 'void *':
        return 'IntPtr', ''  # borrowed Cocoa object (NSArray / NSObject); ownership not transferred
    if ct == 'bool':
        return 'bool', '[return: MarshalAs(UnmanagedType.I1)]'
    if ct == 'char *':
        return 'IntPtr', ''  # UTF-8 string; caller frees via accesskit_string_free
    if ct == 'const struct accesskit_affine *':
        return 'IntPtr', ''  # borrowed pointer into the node
    POINTERS = {
        'struct accesskit_node *', 'struct accesskit_tree *',
        'struct accesskit_tree_update *', 'struct accesskit_custom_action *',
        'struct accesskit_custom_actions *', 'struct accesskit_windows_adapter *',
        'struct accesskit_windows_queued_events *',
        'struct accesskit_windows_subclassing_adapter *',
        'struct accesskit_macos_adapter *',
        'struct accesskit_macos_queued_events *',
        'struct accesskit_macos_subclassing_adapter *',
    }
    if ct in POINTERS:
        return 'IntPtr', ''
    if ct == 'int32_t':
        return 'int', ''
    if ct == 'double':
        return 'double', ''
    if ct in ENUM_CS:
        return ENUM_CS[ct], ''
    # by-value returned structs
    BYVAL_RET = {
        'struct accesskit_affine': 'Affine',
        'struct accesskit_point': 'Point',
        'struct accesskit_size': 'Size',
        'struct accesskit_vec2': 'Vec2',
        'struct accesskit_rect': 'Rect',
        'struct accesskit_tree_id': 'TreeId',
        'struct accesskit_node_ids': 'NodeIds',
        'struct accesskit_lengths': 'Lengths',
        'struct accesskit_opt_node_id': 'OptNodeId',
        'struct accesskit_opt_tree_id': 'OptTreeId',
        'struct accesskit_opt_double': 'OptDouble',
        'struct accesskit_opt_float': 'OptFloat',
        'struct accesskit_opt_index': 'OptIndex',
        'struct accesskit_opt_color': 'OptColor',
        'struct accesskit_opt_coords': 'OptCoords',
        'struct accesskit_opt_bool': 'OptBool',
        'struct accesskit_opt_invalid': 'OptInvalid',
        'struct accesskit_opt_toggled': 'OptToggled',
        'struct accesskit_opt_live': 'OptLive',
        'struct accesskit_opt_text_direction': 'OptTextDirection',
        'struct accesskit_opt_orientation': 'OptOrientation',
        'struct accesskit_opt_sort_direction': 'OptSortDirection',
        'struct accesskit_opt_aria_current': 'OptAriaCurrent',
        'struct accesskit_opt_auto_complete': 'OptAutoComplete',
        'struct accesskit_opt_has_popup': 'OptHasPopup',
        'struct accesskit_opt_list_style': 'OptListStyle',
        'struct accesskit_opt_text_align': 'OptTextAlign',
        'struct accesskit_opt_vertical_offset': 'OptVerticalOffset',
        'struct accesskit_opt_text_decoration': 'OptTextDecoration',
        'struct accesskit_opt_rect': 'OptRect',
        'struct accesskit_opt_text_selection': 'OptTextSelection',
        'struct accesskit_opt_lresult': 'OptLResult',
    }
    if ct in BYVAL_RET:
        return BYVAL_RET[ct], ''
    raise SystemExit(f'Unmapped return type: {ct!r}')


def emit_interop(funcs, banner, decl_consts=True):
    lines = [
        '// <auto-generated>',
        '//   Generated by tools/generate_bindings.py from third-party/accesskit.h (accesskit-c 0.22.2).',
        f'//   {banner}',
        '//   Do not edit by hand; re-run the generator instead.',
        '// </auto-generated>',
        'using System;',
        'using System.Runtime.InteropServices;',
        '',
        'namespace AccessKit;',
        '',
        'internal static partial class Interop',
        '{',
    ]
    if decl_consts:
        lines += [
            '    private const string Lib = "accesskit";',
            '    private const CallingConvention Cc = CallingConvention.Cdecl;',
            '',
        ]
    for ret, name, params in funcs:
        cs_ret, ret_attr = map_return(ret)
        parts = []
        for i, p in enumerate(split_params(params)):
            ctype, pname = split_type_name(p)
            if pname == '':
                # e.g. "void"
                continue
            cs_type, attr = map_param(ctype)
            # avoid C# keyword collisions
            if pname in CS_KEYWORDS:
                pname = '@' + pname
            parts.append(f'{attr}{cs_type} {pname}')
        sig = ', '.join(parts)
        if ret_attr:
            lines.append(f'    [DllImport(Lib, CallingConvention = Cc)] {ret_attr}')
            lines.append(f'    public static extern {cs_ret} {name}({sig});')
        else:
            lines.append(f'    [DllImport(Lib, CallingConvention = Cc)] public static extern {cs_ret} {name}({sig});')
    lines.append('}')
    return '\n'.join(lines)


CS_KEYWORDS = {'params', 'object', 'string', 'value', 'event', 'ref', 'in', 'out', 'base'}


# ---------------------------------------------------------------- Node properties
# Presence flags: (PropertyName, getter_fn_suffix, set/clear share the same suffix).
FLAGS = [
    ('Hidden', 'is_hidden', 'hidden'),
    ('Multiselectable', 'is_multiselectable', 'multiselectable'),
    ('Required', 'is_required', 'required'),
    ('Visited', 'is_visited', 'visited'),
    ('Busy', 'is_busy', 'busy'),
    ('LiveAtomic', 'is_live_atomic', 'live_atomic'),
    ('Modal', 'is_modal', 'modal'),
    ('TouchTransparent', 'is_touch_transparent', 'touch_transparent'),
    ('ReadOnly', 'is_read_only', 'read_only'),
    ('Disabled', 'is_disabled', 'disabled'),
    ('Italic', 'is_italic', 'italic'),
    ('ClipsChildren', 'clips_children', 'clips_children'),
    ('IsLineBreakingObject', 'is_line_breaking_object', 'is_line_breaking_object'),
    ('IsPageBreakingObject', 'is_page_breaking_object', 'is_page_breaking_object'),
    ('IsSpellingError', 'is_spelling_error', 'is_spelling_error'),
    ('IsGrammarError', 'is_grammar_error', 'is_grammar_error'),
    ('IsSearchMatch', 'is_search_match', 'is_search_match'),
    ('IsSuggestion', 'is_suggestion', 'is_suggestion'),
]

# Optional bool: (PropertyName, getter_suffix, set/clear_suffix)
OPT_BOOLS = [
    ('Expanded', 'is_expanded', 'expanded'),
    ('Selected', 'is_selected', 'selected'),
]

DOUBLES = ['scroll_x', 'scroll_x_min', 'scroll_x_max', 'scroll_y', 'scroll_y_min',
           'scroll_y_max', 'numeric_value', 'min_numeric_value', 'max_numeric_value',
           'numeric_value_step', 'numeric_value_jump']

FLOATS = ['font_size', 'font_weight']

INDICES = ['row_count', 'column_count', 'row_index', 'column_index', 'row_span',
           'column_span', 'level', 'size_of_set', 'position_in_set']

COLORS = ['color_value', 'background_color', 'foreground_color']

DECORATIONS = ['overline', 'strikethrough', 'underline']

# (suffix, EnumType)
ENUM_PROPS = [
    ('invalid', 'Invalid'), ('toggled', 'Toggled'), ('live', 'Live'),
    ('text_direction', 'TextDirection'), ('orientation', 'Orientation'),
    ('sort_direction', 'SortDirection'), ('aria_current', 'AriaCurrent'),
    ('auto_complete', 'AutoComplete'), ('has_popup', 'HasPopup'),
    ('list_style', 'ListStyle'), ('text_align', 'TextAlign'),
    ('vertical_offset', 'VerticalOffset'),
]

# Single optional node id: suffixes (get fn = node_<suffix>, set/clear use <suffix>)
NODE_ID_PROPS = ['active_descendant', 'error_message', 'in_page_link_target',
                 'member_of', 'next_on_line', 'previous_on_line', 'popup_for']


def pascal(snake):
    return ''.join(p.capitalize() for p in snake.split('_'))


def emit_node():
    L = []
    L += [
        '// <auto-generated>',
        '//   Generated by tools/generate_bindings.py from third-party/accesskit.h (accesskit-c 0.22.2).',
        '//   The regular (single-value) node properties. Marshaling-heavy members (strings, id lists,',
        '//   custom actions, transform, actions) are hand-written in Node.cs.',
        '//   Do not edit by hand; re-run the generator instead.',
        '// </auto-generated>',
        'using System;',
        '',
        'namespace AccessKit;',
        '',
        'public sealed partial class Node',
        '{',
    ]

    def doc(s):
        L.append(f'    /// <summary>{s}</summary>')

    # presence flags
    for prop, getter, sc in FLAGS:
        doc(f'Presence flag <c>{sc}</c>.')
        L.append(f'    public bool {prop}')
        L.append('    {')
        L.append(f'        get => Interop.accesskit_node_{getter}(_handle);')
        L.append(f'        set {{ if (value) Interop.accesskit_node_set_{sc}(_handle); else Interop.accesskit_node_clear_{sc}(_handle); }}')
        L.append('    }')
        L.append('')

    # optional bools
    for prop, getter, sc in OPT_BOOLS:
        doc(f'Tri-state <c>{sc}</c> (null = unset).')
        L.append(f'    public bool? {prop}')
        L.append('    {')
        L.append(f'        get {{ var o = Interop.accesskit_node_{getter}(_handle); return o.HasValue != 0 ? o.Value != 0 : (bool?)null; }}')
        L.append(f'        set {{ if (value.HasValue) Interop.accesskit_node_set_{sc}(_handle, value.Value); else Interop.accesskit_node_clear_{sc}(_handle); }}')
        L.append('    }')
        L.append('')

    # doubles
    for s in DOUBLES:
        doc(f'<c>{s}</c> (null = unset).')
        L.append(f'    public double? {pascal(s)}')
        L.append('    {')
        L.append(f'        get {{ var o = Interop.accesskit_node_{s}(_handle); return o.HasValue != 0 ? o.Value : (double?)null; }}')
        L.append(f'        set {{ if (value.HasValue) Interop.accesskit_node_set_{s}(_handle, value.Value); else Interop.accesskit_node_clear_{s}(_handle); }}')
        L.append('    }')
        L.append('')

    # floats
    for s in FLOATS:
        doc(f'<c>{s}</c> (null = unset).')
        L.append(f'    public float? {pascal(s)}')
        L.append('    {')
        L.append(f'        get {{ var o = Interop.accesskit_node_{s}(_handle); return o.HasValue != 0 ? o.Value : (float?)null; }}')
        L.append(f'        set {{ if (value.HasValue) Interop.accesskit_node_set_{s}(_handle, value.Value); else Interop.accesskit_node_clear_{s}(_handle); }}')
        L.append('    }')
        L.append('')

    # indices (size_t)
    for s in INDICES:
        doc(f'<c>{s}</c> (null = unset).')
        L.append(f'    public int? {pascal(s)}')
        L.append('    {')
        L.append(f'        get {{ var o = Interop.accesskit_node_{s}(_handle); return o.HasValue != 0 ? (int)(uint)o.Value : (int?)null; }}')
        L.append(f'        set {{ if (value.HasValue) Interop.accesskit_node_set_{s}(_handle, (UIntPtr)(uint)value.Value); else Interop.accesskit_node_clear_{s}(_handle); }}')
        L.append('    }')
        L.append('')

    # colors
    for s in COLORS:
        doc(f'<c>{s}</c> (null = unset).')
        L.append(f'    public Color? {pascal(s)}')
        L.append('    {')
        L.append(f'        get {{ var o = Interop.accesskit_node_{s}(_handle); return o.HasValue != 0 ? o.Value : (Color?)null; }}')
        L.append(f'        set {{ if (value.HasValue) Interop.accesskit_node_set_{s}(_handle, value.Value); else Interop.accesskit_node_clear_{s}(_handle); }}')
        L.append('    }')
        L.append('')

    # text decorations
    for s in DECORATIONS:
        doc(f'<c>{s}</c> text decoration (null = unset).')
        L.append(f'    public TextDecoration? {pascal(s)}')
        L.append('    {')
        L.append(f'        get {{ var o = Interop.accesskit_node_{s}(_handle); return o.HasValue != 0 ? o.Value : (TextDecoration?)null; }}')
        L.append(f'        set {{ if (value.HasValue) Interop.accesskit_node_set_{s}(_handle, value.Value); else Interop.accesskit_node_clear_{s}(_handle); }}')
        L.append('    }')
        L.append('')

    # enum properties
    for s, etype in ENUM_PROPS:
        doc(f'<c>{s}</c> (null = unset).')
        L.append(f'    public {etype}? {pascal(s)}')
        L.append('    {')
        L.append(f'        get {{ var o = Interop.accesskit_node_{s}(_handle); return o.HasValue != 0 ? o.Value : ({etype}?)null; }}')
        L.append(f'        set {{ if (value.HasValue) Interop.accesskit_node_set_{s}(_handle, value.Value); else Interop.accesskit_node_clear_{s}(_handle); }}')
        L.append('    }')
        L.append('')

    # single optional node ids
    for s in NODE_ID_PROPS:
        doc(f'<c>{s}</c> node id (null = unset).')
        L.append(f'    public ulong? {pascal(s)}')
        L.append('    {')
        L.append(f'        get {{ var o = Interop.accesskit_node_{s}(_handle); return o.HasValue != 0 ? o.Value : (ulong?)null; }}')
        L.append(f'        set {{ if (value.HasValue) Interop.accesskit_node_set_{s}(_handle, value.Value); else Interop.accesskit_node_clear_{s}(_handle); }}')
        L.append('    }')
        L.append('')

    # bounds (opt_rect)
    doc('Bounding box in the window coordinate space (y-down); null = unset.')
    L.append('    public Rect? Bounds')
    L.append('    {')
    L.append('        get { var o = Interop.accesskit_node_bounds(_handle); return o.HasValue != 0 ? o.Value : (Rect?)null; }')
    L.append('        set { if (value.HasValue) Interop.accesskit_node_set_bounds(_handle, value.Value); else Interop.accesskit_node_clear_bounds(_handle); }')
    L.append('    }')
    L.append('')

    # text selection (opt_text_selection)
    doc('Text selection within this node (null = unset).')
    L.append('    public TextSelection? TextSelection')
    L.append('    {')
    L.append('        get { var o = Interop.accesskit_node_text_selection(_handle); return o.HasValue != 0 ? o.Value : (TextSelection?)null; }')
    L.append('        set { if (value.HasValue) Interop.accesskit_node_set_text_selection(_handle, value.Value); else Interop.accesskit_node_clear_text_selection(_handle); }')
    L.append('    }')
    L.append('')

    # tree id (opt_tree_id)
    doc('The id of a subtree hosted by this node (null = unset).')
    L.append('    public TreeId? TreeId')
    L.append('    {')
    L.append('        get { var o = Interop.accesskit_node_tree_id(_handle); return o.HasValue != 0 ? o.Value : (TreeId?)null; }')
    L.append('        set { if (value.HasValue) Interop.accesskit_node_set_tree_id(_handle, value.Value); else Interop.accesskit_node_clear_tree_id(_handle); }')
    L.append('    }')
    L.append('')

    L.append('}')
    return '\n'.join(L)


def main():
    src = strip_comments(open(HEADER, encoding='utf-8').read())
    src_nodirective = re.sub(r'^\s*#.*$', '', src, flags=re.M)

    enums = parse_enums(src)
    all_funcs = parse_funcs(src_nodirective)

    # Cross-platform + Windows functions (exported by the bundled win-x64 accesskit.dll).
    OTHER = ('android', 'ios', 'macos', 'unix')
    core_funcs = [f for f in all_funcs if not any(o in f[1] for o in OTHER)]
    # macOS adapter functions (exported by libaccesskit.dylib).
    macos_funcs = [f for f in all_funcs if 'macos' in f[1]]

    def write(name, text):
        open(os.path.join(OUT_DIR, name), 'w', encoding='utf-8', newline='\n').write(text + '\n')

    write('Enums.Generated.cs', emit_enums(enums))
    write('Interop.Generated.cs',
          emit_interop(core_funcs, 'One DllImport per function exported by the bundled win-x64 accesskit.dll.'))
    write('Interop.Macos.Generated.cs',
          emit_interop(macos_funcs,
                       'The macOS adapter functions (libaccesskit.dylib; only resolvable on macOS).',
                       decl_consts=False))
    write('Node.Generated.cs', emit_node())
    print(f'enums: {len([e for e in enums if e[0] not in SKIP_ENUMS])}, '
          f'core functions: {len(core_funcs)}, macOS functions: {len(macos_funcs)}')


if __name__ == '__main__':
    main()
